### ISSUE TITLE
Django 1.8 compatibilty issue

### ISSUE THREAD

**Issue by sharad5** [payu-india/PayU-Integration-Kit-Django#4]
Throwing No module named #No module named lorem_ipsum
Traceback (most recent call last):
  File "/home/sharad/dev/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 108, in get_response
    response = middleware_method(request)
  File "/home/sharad/dev/env/local/lib/python2.7/site-packages/django/middleware/common.py", line 74, in process_request
    if (not urlresolvers.is_valid_path(request.path_info, urlconf) and
  File "/home/sharad/dev/env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 647, in is_valid_path
    resolve(path, urlconf)
  File "/home/sharad/dev/env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 522, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/sharad/dev/env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/home/sharad/dev/env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/sharad/dev/env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/sharad/dev/Test/PayU-Integration-Kit-Django/PayU/demo/democart/urls.py", line 4, in <module>
    (r'^order/', include('cart.urls')),
  File "/home/sharad/dev/env/local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/sharad/dev/Test/PayU-Integration-Kit-Django/PayU/demo/cart/urls.py", line 2, in <module>
    from cart import views
  File "/home/sharad/dev/Test/PayU-Integration-Kit-Django/PayU/demo/cart/views.py", line 11, in <module>
    from django.contrib.webdesign.lorem_ipsum import sentence as lorem_ipsum
ImportError: No module named lorem_ipsum

Maybe because this is deprecated since version 1.8.

**Comment by shashankvivek** [comment]
Having same issue with django 1.8.5

**Comment by shashankvivek** [comment]
django_version = django.VERSION[0:2]
# The lorem template tag is now included in the built-in tags
if django_version >= (1, 8):
    from django.utils import lorem_ipsum
else:
    from django.contrib.webdesign import lorem_ipsum   

Worked !
